/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CreateSupplier: typeof import('./src/components/CreateSupplier.vue')['default']
    Ex: typeof import('./src/components/ex.vue')['default']
    GraphicView: typeof import('./src/components/graphicView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    TableEmployees: typeof import('./src/components/TableEmployees.vue')['default']
  }
}
