/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Component: typeof import('./src/components/Component.vue')['default']
    CreateProduct: typeof import('./src/components/CreateProduct.vue')['default']
    CreateSupplier: typeof import('./src/components/CreateSupplier.vue')['default']
    GenericTable: typeof import('./src/components/GenericTable.vue')['default']
    ModalRegisterAndEdit: typeof import('./src/components/ModalRegisterAndEdit.vue')['default']
    ModalRegisterSupplier: typeof import('./src/components/ModalRegisterSupplier.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProductsTable: typeof import('./src/components/ProductsTable.vue')['default']
    Register: typeof import('./src/components/register.vue')['default']
    RegisterEmployees: typeof import('./src/components/RegisterEmployees.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableEmployees: typeof import('./src/components/TableEmployees.vue')['default']
    TransactionTable: typeof import('./src/components/TransactionTable.vue')['default']
  }
}
